name: Linux - Cache Dependencies
on:
  workflow_dispatch:

jobs:
  cache-vcpkg-qt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install System Build Tools
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential pkg-config libx11-dev libxkbcommon-dev libgl1-mesa-dev libsecret-1-dev

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Build and Cache Dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            ${{ github.workspace }}/vcpkg
          key: linux-vcpkg-qt6-8-3-${{ hashFiles('vcpkg.json') }}

      - name: Run Vcpkg Install
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install --triplet x64-linux \
            --x-install-root="${{ github.workspace }}/vcpkg_installed"