name: Release Notesman

on:
  workflow_dispatch:  # chỉ chạy thủ công

jobs:
  build-linux:
    name: Build & Release Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache vcpkg installed
        uses: actions/cache@v3
        with:
          path: ./vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Setup CMake
        uses: lukka/get-cmake@v4
        with:
          cmake-version: "3.27.5"

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git ./vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install --manifest

      - name: Configure & Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config Release

      - name: Package binaries
        run: tar -czf notesman-linux.tar.gz -C build Release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Notesman v1.0.0
          draft: false
          prerelease: false
          body: "Initial release of Notesman."

      - name: Upload Linux binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./notesman-linux.tar.gz
          asset_name: notesman-linux.tar.gz
          asset_content_type: application/gzip
