name: Release Notesman

on:
  workflow_dispatch:  # chỉ chạy thủ công

jobs:
  build-linux:
    name: Build & Release Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache vcpkg installed
        uses: actions/cache@v3
        with:
          path: ./vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmake-version: "3.31.0"

      - name: Setup VCPKG Tools
        uses: actions/cache/restore@v3
        id: cache-vcpkg-source
        with:
          path: ./vcpkg
          key: ${{ runner.os }}-vcpkg-source
      
      - name: Clone and Bootstrap VCPKG
        # Chỉ chạy nếu cache-hit không thành công
        if: steps.cache-vcpkg-source.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git ./vcpkg
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Cache VCPKG Tools
        uses: actions/cache/save@v3
        if: steps.cache-vcpkg-source.outputs.cache-hit != 'true'
        with:
          path: ./vcpkg
          key: ${{ runner.os }}-vcpkg-source
          
      - name: Install vcpkg
        env:
          VCPKG_DEFAULT_TRIPLET: x64-linux-dynamic
          VCPKG_DEFAULT_HOST_TRIPLET: x64-linux-dynamic
        run: |
          git clone https://github.com/microsoft/vcpkg.git ./vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install

      - name: Configure & Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config Release

      - name: Package binaries
        run: tar -czf notesman-linux.tar.gz -C build Release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Notesman v1.0.0
          draft: false
          prerelease: false
          body: "Initial release of Notesman."

      - name: Upload Linux binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./notesman-linux.tar.gz
          asset_name: notesman-linux.tar.gz
          asset_content_type: application/gzip
