name: Tag trigger

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Notesman ${{ github.ref_name }}"
          body: |
            **Notesman ${{ github.ref_name }}**

            This release includes builds for:

            <!-- LINUX_SECTION_START -->
            <!-- LINUX_SECTION_END -->

            <!-- WINDOWS_SECTION_START -->
            <!-- WINDOWS_SECTION_END -->

            ---
            _Generated automatically by GitHub Actions._
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_AUTHOR_PAT }}
